# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: pretty
relative_permalinks: false

# Setup
title:               ""
tagline:             'a giraffe on cliff'
description:         'A cosy place to keep my homepage and blog.'
url:                 "http://amrollah.me"
baseurl:             ""
paginate:            5
comments: true
show_related_posts: false

# About/contact
author:
  name:              Amrollah
  url:               "https://twitter.com/amrollah_seif"
  email:             a.seif67@gmail.com

disqus_shortname: "amrollah"
google_analytics: UA-8031131-6

# social footer
github: http://github.com/amrollah
facebook: http://facebook.com/amrollah.seif
twitter: http://twitter.com/amrollah_seif
linkedin: http://ch.linkedin.com/in/amrollah
instagram: https://www.instagram.com/amrollah.seif/

# Custom vars
version:             1.1.0
